### ISSUE TITLE
Off-mode not working?

### ISSUE THREAD

**Issue by skefre** [Danielhiversen/pymill#9]
Setting the heaters off don't seem to work with HA? (but it work in the mill-app).

2018-10-28 23:31:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 224, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 493, in turn_on
    raise NotImplementedError()
NotImplementedError

**Comment by Danielhiversen** [comment]
How do you call turn_off service?
https://github.com/home-assistant/home-assistant/blob/21870e2167f7766a5e3aff73021d36b6e33f98f1/homeassistant/components/climate/mill.py#L159

**Comment by skefre** [comment]
So it should work now? :)

**Comment by Danielhiversen** [comment]
How do you call the turn_off service?

**Comment by skefre** [comment]
Using the "climate.turn_off" command for the entity.

**Comment by Danielhiversen** [comment]
Use `async_turn_off`

**Comment by skefre** [comment]
Might be a silly question, but how would the automation be like in this case? Like this, or?

automation:
  trigger:
    platform: time
    at: "07:15:00"
  action:
    - service: climate.async_turn_off
       entity_id: climate.gjesterom

**Comment by Danielhiversen** [comment]
That might not be supported.
This a general HA issue, so please open an issue here: https://github.com/home-assistant/home-assistant/issues/new
